### PR TITLE
Add support for kernel32.OutputDebugStringA/W

### PR DESCRIPTION
**Pull request by re-fox**
Function has no return value, so this is just a stub for formatting the output of these calls.

### CODE REVIEW

**Comment by drewvis** [comment]
Just a quick comment on the ansi vs unicode functions. *A/*W functions can actually be handled in a single handler by simply dropped the A/W. The function name is passed to the handler so it can determine the character width.

A good example similar to OutputDebugString is MessageBox shown here: https://github.com/fireeye/speakeasy/blob/master/speakeasy/winenv/api/usermode/user32.py#L125

**Comment by re-fox** [comment]
Thanks for the information, I hadn't realized that.

Is this the correct way to go about it?
```
    @apihook('OutputDebugString', argc=1)
    def OutputDebugString(self, emu, argv, ctx={}):
        '''
        void OutputDebugStringA(
            LPCSTR lpOutputString
        );
        '''
        _str, = argv
        cw = self.get_char_width(ctx)
        argv[0] = self.read_mem_string(_str, cw)
```

**Comment by drewvis** [comment]
Yep! looks good.

**Comment by re-fox** [comment]
Ok, I made the changes, thanks for the comments.  Still learning the inner workings of speakeasy.

**Pull request merged**
